### PR TITLE
add summer update to website

### PR DESCRIPTION
**Pull request by irapha**
Hey Natalia,

I've added the doc (including all links) to the website. I did not spend a ton of time making it pretty, however (maybe someone else can work on that a bit?).

You can check how it looks like locally by downloading jekyll and running `jekyll serve` from the repo directory, then navigating to localhost:4000. If you make changes and want to commit, just make sure to stop the jekyll serving and run `jekyll clean` so you don't commit temp files :)

Cheers,
-Rapha

### CODE REVIEW

**Comment by nbilenko** [comment]
Looks great! Is it possible to style the tabs like buttons to indicate that they are clickable?

**Comment by irapha** [comment]
Done!

**Comment by nbilenko** [comment]
LGTM!

**Review by nbilenko — APPROVED** [review]
🚢

**Pull request merged**
